name: Weather Alert

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  weather-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r "Supplementary task 1/requirements.txt"

      - name: Run Weather Alert
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
<<<<<<< HEAD
        run: python "Supplementary task 1/weather_alert.py"
=======
        run: python "Supplementary task 1/weather_alert.py"
>>>>>>> 06c177efc3d17c80d7f394141edd06e1a1ea7438
